### ISSUE TITLE
Неправильно работает RELOAD_ON_CHANGE

### ISSUE THREAD

**Issue by Golem14** [DevelopmentOnTheEdge/be5#115]
1) Должно срабатывать по потере фокуса, сейчас на каждый введенный символ.
2) Не должна вызываться валидация. По крайней мере на остальные элементы формы.

**Comment by QProgS** [comment]
f89148813e6376fd08a038fede26e326b2520527 validate only reload control in generate with RELOAD_CONTROL_NAME

**Comment by QProgS** [comment]
переделал reloadOnChange по потере фокуса для текстовых полей
https://github.com/DevelopmentOnTheEdge/be5-react/commit/24e6806a5cd1ac329d77d8746e736455ac501392
https://github.com/DevelopmentOnTheEdge/beanexplorer-react/commit/6360adfebde516c09c1a457df4842cd773ad9191
